### ISSUE TITLE
Both Percentages count being 0

### ISSUE THREAD

**Issue by SolarionSch** [sujalgoel/wyr#1]
Sometimes both of the percentage count will be 0 for unknown reason. No errors pop up in console.

**Comment by sujalgoel** [comment]
Please share a screen shot of what you are saying

**Comment by SolarionSch** [comment]
![Screenshot_20210704_222658_com.discord.jpg](https://user-images.githubusercontent.com/66461609/124388790-f9820980-dd16-11eb-97e6-7c156e1aad49.jpg)

**Comment by sujalgoel** [comment]
![](https://averylongdomainyesitisverylongasyoucanseedudesee.tk/static/f7d78a5ea9331eb07599a10b34a3cf77.png)

**Comment by sujalgoel** [comment]
and if you don't mind then could you please share the code?

**Comment by SolarionSch** [comment]
It only happens with some of the Questions. Not all will display as 0%.

**Comment by sujalgoel** [comment]
then it is possible those got no votes or they are new

**Comment by SolarionSch** [comment]
I see.
